import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title key="title">Random Quote</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          {" "}
          <a
            href="/randomQuote"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Quote <span>-&gt;</span>
            </h2>
            <p>Get a random quote</p>
          </a>
        </div>
      </main>
    </>
  );
}
